server:
  port: 8080

spring:
  application:
    name: travelapps-service

  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/travel_db
    username: root
    password: root
